define(["exports","./lit-element-34339bae","./StyleableMixin-9aebdd05","./ThemeableMixin-c1113bda","./NativeReflectorMixin-ee6c4eac"],function(a,b,c,d,e){'use strict';function f(){var a=b._taggedTemplateLiteral(["\n      ","\n      <form id=\"native\">\n        <slot></slot>\n      </form>\n    "]);return f=function(){return a},a}/* globals customElements */var g=/*#__PURE__*/function(a){function c(){return b._classCallCheck(this,c),b._possibleConstructorReturn(this,b._getPrototypeOf(c).apply(this,arguments))}return b._inherits(c,a),b._createClass(c,[{key:"reportValidity",value:function(){// Check validity in form
var a=!0,b=!0,c=!1,d=void 0;try{for(var e,f,g=this.elements[Symbol.iterator]();!(b=(e=g.next()).done);b=!0)f=e.value,"function"==typeof f.reportValidity&&(f.setCustomValidity(""),!f.reportValidity()&&(a=!1))}catch(a){c=!0,d=a}finally{try{b||null==g["return"]||g["return"]()}finally{if(c)throw d}}return a}},{key:"checkValidity",value:function(){// Check validity in form
var a=!0,b=!0,c=!1,d=void 0;// if (!this.native.checkValidity()) valid = false
try{for(var e,f,g=this.elements[Symbol.iterator]();!(b=(e=g.next()).done);b=!0)f=e.value,"function"==typeof f.checkValidity&&(f.setCustomValidity(""),!f.checkValidity()&&(a=!1))}catch(a){c=!0,d=a}finally{try{b||null==g["return"]||g["return"]()}finally{if(c)throw d}}return a}},{key:"setFormElementValue",value:function(a,c){var d=this,f=b._toConsumableArray(this.elements).find(function(b){return d._radioElement(b)?b.name===a&&b.value===c:b.name===a});if(f){// Get the original value
var e=this._getElementValueSource(f);// CHECKBOXES
if(this._checkboxElement(f))f[e]=!!c;else if(this._radioElement(f)){f[e]=!0;var g=b._toConsumableArray(this.elements).filter(function(a){return f!==a&&d._radioElement(f)}),h=!0,i=!1,j=void 0;try{for(var k,l,m=g[Symbol.iterator]();!(h=(k=m.next()).done);h=!0)l=k.value,l[e]=!1;// SELECT
// Selectable elements (with prop selectedIndex)
}catch(a){i=!0,j=a}finally{try{h||null==m["return"]||m["return"]()}finally{if(i)throw j}}}else this._selectElement(f)?c?f[e]=c:f.selectedIndex=0:f[e]=c}}},{key:"getFormElementValue",value:function(a){var c=this,d=b._toConsumableArray(this.elements).filter(function(b){return b.name===a});if(!d.length)return void console.error("Trying to set",a,"but no such element in form");if(1===d.length){var e=d[0],f=this._getElementValueSource(e);return this._checkboxElement(e)?e[f]?e.value?e.value:"on":void 0:this._selectElement(e)?e[f]:e[f]}var g=d.filter(function(a){return!c._radioElement(a)});if(g.length)return void console.error("Duplicate name",a,"for non-radio elements");var h=d.find(function(a){var b=c._getElementValueSource(a);return a[b]});return h?h.value:void 0}},{key:"reset",value:function(){if(this.native){this.native.reset();// TODO: Adjust this for radios in a nice sensible way
var a=!0,b=!1,c=void 0;try{for(var d,e=this.elements[Symbol.iterator]();!(a=(d=e.next()).done);a=!0){var f=d.value,g=this._getElementValueSource(f);f[g]=this._radioElement(f)?null!==f.getAttribute(g):this._checkboxElement(f)?null!==f.getAttribute(g):f.getAttribute(g)}}catch(a){b=!0,c=a}finally{try{a||null==e["return"]||e["return"]()}finally{if(b)throw c}}}}},{key:"_selectElement",value:function(a){return"undefined"!=typeof a.selectedIndex||null!==a.getAttribute("as-select")}},{key:"_checkboxElement",value:function(a){return"checkbox"===a.type||null!==a.getAttribute("as-checkbox")}},{key:"_radioElement",value:function(a){return"radio"===a.type||null!==a.getAttribute("as-radio")}},{key:"_getElementValueSource",value:function(a){return"checkbox"===a.type||"radio"===a.type?"checked":a.getAttribute("value-source")?a.getAttribute("value-source"):"value"}},{key:"render",value:function(){return b.html(f(),this.customStyle)}},{key:"reflectProperties",get:function(){return[].concat(b._toConsumableArray(b._get(b._getPrototypeOf(c.prototype),"reflectProperties",this)),["length","name","method","target","action","encoding","enctype","acceptCharset","autocomplete","noValidate","requestAutocomplete","submit"])}},{key:"elements",get:function(){// A tags (links) can have "name", filter them out
return b._toConsumableArray(this.querySelectorAll("[name]")).filter(function(a){return"A"!==a.tagName})}}]),c}(d.ThemeableMixin("nn-form")(c.StyleableMixin(e.NativeReflectorMixin(b.LitElement))));customElements.define("nn-form",g),a.NnForm=g,Object.defineProperty(a,"__esModule",{value:!0})});
